[tool.poetry]
name = "budgetwise"
version = "0.1.0"
description = "hackathon project"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = ">=0.118.0"
uvicorn = {extras = ["standard"], version = ">=0.30.0"}
pydantic = ">=2.0.0"
supabase = ">=2.0.0"
python-dotenv = ">=1.0.0"
httpx = ">=0.27.0"
openai = ">=1.12.0"
elevenlabs = ">=0.2.24"
tenacity = ">=8.2.0"
<<<<<<< HEAD
sqlalchemy = "^2.0.43"
=======
numpy = ">=1.26.0"
>>>>>>> 2232ae53bc6529c55c69235f63d4d8f3bb4e5347


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
